# -*- coding: utf-8 -*-
"""MusiCNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ldz20zTumkTYUokKLgNx6Q8ffLiRwg1J

## Installing Required Dependencies
"""

!pip install tensorflow==2.4
import tensorflow as tf
print(tf.__version__)

!pip install musicnn

"""### Accessign required features from the library"""

from musicnn.tagger import top_tags
from musicnn.extractor import extractor

from google.colab import drive
drive.mount('/content/drive')

print(top_tags('/content/drive/MyDrive/dataset/sample1/Clip 1.mp3'))
print(top_tags('/content/drive/MyDrive/dataset/sample1/Clip 2.mp3'))

"""### Generating Cos Sim between the song pairs"""

in_length = 28 # seconds

file_name1 = "/content/drive/MyDrive/dataset/sample15/Clip 1.mp3" #song 1
file_name2 = "/content/drive/MyDrive/dataset/sample15/Clip 2.mp3" #song 2

"""### Extracting features from both the songs"""

from musicnn.extractor import extractor
taggram1, tags1, features1 = extractor(file_name1, model='MTT_musicnn', extract_features=True)
taggram2, tags2, features2 = extractor(file_name2, model='MTT_musicnn', extract_features=True)

"""### Computing Cosine Similarity Score"""

from scipy import spatial
cosine_sim = (1 - spatial.distance.cosine(features1["penultimate"][8], features2["penultimate"][8])) #dimension = (time steps,)
print(cosine_sim)